### ISSUE TITLE
As a developer, I want to detect the current page and run code only on the appropriate page

### ISSUE THREAD

**Issue by GreenMan36** [GreenMan36/StartOut#1]
# Description
Currently, the code can be executed on any page, which may lead to issues. Implementing this feature would enable running the code on a per-page basis, allowing the easy creation of page-specific functionalities without risking spaghetti code that would need to be cleaned up later.

# Tasks
- [x] Detect the current page
- [x]  Execute the jobs code only if the user is on the jobs page
- [x]  Display an error message if no valid page is detected
- [x]  Clean up any elements created by the bookmarklet on the wrong page after displaying the error message

# DOD
All code has been pushed, refactored at least once, tested manually, and merged with the development branch
